[pytest]
filterwarnings =
    ignore:ARC4 has been moved to cryptography\.hazmat\.decrepit\.ciphers\.algorithms\.ARC4.*:cryptography.utils.CryptographyDeprecationWarning
    ignore:You are using a Python version \(3\.10\.0\) which Google will stop supporting in new releases of google\.api_core.*:FutureWarning:google\.api_core\._python_version_support